on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: |
          python -m pip install --quiet --upgrade pip
          python -m pip install --quiet cookiecutter
          python -m cookiecutter . --no-input
          xyz/buildkite/build-test-push.sh
